In [1]:
import pandas as pd
import numpy as np

### sample_data.txt 전처리

In [2]:
# PFI 혹은 PFI.time이 Nan인 인스턴스 없음
df_sample = pd.read_csv("final_data/sample_data.txt", sep="\t")
df_sample.shape

(742, 34)

In [3]:
df_sample.head()

,V1,bcr_patient_barcode,type,age_at_initial_pathologic_diagnosis,gender,race,ajcc_pathologic_tumor_stage,clinical_stage,histological_type,histological_grade,...,residual_tumor,OS,OS.time,DSS,DSS.time,DFI,DFI.time,PFI,PFI.time,Redaction
0,505,TCGA-3C-AAAU,BRCA,55.0,FEMALE,WHITE,Stage X,[Not Applicable],Infiltrating Lobular Carcinoma,[Not Available],...,NaN,0,4047.0,0.0,4047.0,1.0,1808.0,1,1808.0,NaN
1,506,TCGA-3C-AALI,BRCA,50.0,FEMALE,BLACK OR AFRICAN AMERICAN,Stage IIB,[Not Applicable],Infiltrating Ductal Carcinoma,[Not Available],...,NaN,0,4005.0,0.0,4005.0,0.0,4005.0,0,4005.0,NaN
2,507,TCGA-3C-AALJ,BRCA,62.0,FEMALE,BLACK OR AFRICAN AMERICAN,Stage IIB,[Not Applicable],Infiltrating Ductal Carcinoma,[Not Available],...,NaN,0,1474.0,0.0,1474.0,0.0,1474.0,0,1474.0,NaN
3,508,TCGA-3C-AALK,BRCA,52.0,FEMALE,BLACK OR AFRICAN AMERICAN,Stage IA,[Not Applicable],Infiltrating Ductal Carcinoma,[Not Available],...,NaN,0,1448.0,0.0,1448.0,NaN,NaN,0,1448.0,NaN
4,509,TCGA-4H-AAAK,BRCA,50.0,FEMALE,WHITE,Stage IIIA,[Not Applicable],Infiltrating Lobular Carcinoma,[Not Available],...,NaN,0,348.0,0.0,348.0,0.0,348.0,0,348.0,NaN

In [4]:
df_sample = df_sample.dropna(subset=["bcr_patient_barcode", "age_at_initial_pathologic_diagnosis", "gender", "race", "PFI", "PFI.time"])
df_sample.shape

(741, 34)

In [5]:
df_sample.columns

Index(['V1', 'bcr_patient_barcode', 'type',
       'age_at_initial_pathologic_diagnosis', 'gender', 'race',
       'ajcc_pathologic_tumor_stage', 'clinical_stage', 'histological_type',
       'histological_grade', 'initial_pathologic_dx_year', 'menopause_status',
       'birth_days_to', 'vital_status', 'tumor_status', 'last_contact_days_to',
       'death_days_to', 'cause_of_death', 'new_tumor_event_type',
       'new_tumor_event_site', 'new_tumor_event_site_other',
       'new_tumor_event_dx_days_to', 'treatment_outcome_first_course',
       'margin_status', 'residual_tumor', 'OS', 'OS.time', 'DSS', 'DSS.time',
       'DFI', 'DFI.time', 'PFI', 'PFI.time', 'Redaction'],
      dtype='object')

In [6]:
df_sample_selected = df_sample[["bcr_patient_barcode", "age_at_initial_pathologic_diagnosis", "gender", "race", "PFI", "PFI.time"]]

In [7]:
df_sample_selected["race"].unique()

array(['WHITE', 'BLACK OR AFRICAN AMERICAN', 'ASIAN', '[Not Available]',
       'AMERICAN INDIAN OR ALASKA NATIVE', '[Not Evaluated]'],
      dtype=object)

In [8]:
df_sample_selected["BLACK OR AFRICAN AMERICAN"] = (df_sample_selected["race"] == "BLACK OR AFRICAN AMERICAN").astype(int)
df_sample_selected["ASIAN"] = (df_sample_selected["race"] == "ASIAN").astype(int)
df_sample_selected["AMERICAN INDIAN OR ALASKA NATIVE"] = (df_sample_selected["race"] == "AMERICAN INDIAN OR ALASKA NATIVE").astype(int)

/tmp/ipykernel_1160374/2904746999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sample_selected["BLACK OR AFRICAN AMERICAN"] = (df_sample_selected["race"] == "BLACK OR AFRICAN AMERICAN").astype(int)
/tmp/ipykernel_1160374/2904746999.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sample_selected["ASIAN"] = (df_sample_selected["race"] == "ASIAN").astype(int)
/tmp/ipykernel_1160374/2904746999.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sample_selected["AMERICAN INDIAN OR ALASKA NATIVE"] = (df_sample_selected["race"] == "AMERICAN INDIAN OR ALASKA NATIVE").astype(int)

In [9]:
df_sample_selected["gender"] = df_sample_selected["gender"].apply(lambda x: int(x == "MALE"))

/tmp/ipykernel_1160374/2580725090.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sample_selected["gender"] = df_sample_selected["gender"].apply(lambda x: int(x == "MALE"))

In [10]:
df_sample_selected["race_filter"] = df_sample_selected["race"].apply(lambda x: int(x in ["WHITE", "BLACK OR AFRICAN AMERICAN", "ASIAN", "AMERICAN INDIAN OR ALASKA NATIVE"]))
df_sample_selected = df_sample_selected[df_sample_selected["race_filter"] == True]

/tmp/ipykernel_1160374/1575545753.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sample_selected["race_filter"] = df_sample_selected["race"].apply(lambda x: int(x in ["WHITE", "BLACK OR AFRICAN AMERICAN", "ASIAN", "AMERICAN INDIAN OR ALASKA NATIVE"]))

In [11]:
df_sample_selected["race"].unique()

array(['WHITE', 'BLACK OR AFRICAN AMERICAN', 'ASIAN',
       'AMERICAN INDIAN OR ALASKA NATIVE'], dtype=object)

In [12]:
df_clinical = df_sample_selected[["age_at_initial_pathologic_diagnosis", "gender", "BLACK OR AFRICAN AMERICAN", "ASIAN", "AMERICAN INDIAN OR ALASKA NATIVE"]]
df_clinical.index = range(df_clinical.shape[0])
array_clinical = df_clinical.to_numpy()
array_clinical.shape

(726, 5)

In [13]:
array_clinical

array([[55.,  0.,  0.,  0.,  0.],
       [50.,  0.,  1.,  0.,  0.],
       [62.,  0.,  1.,  0.,  0.],
       ...,
       [68.,  0.,  0.,  0.,  0.],
       [61.,  0.,  0.,  0.,  0.],
       [46.,  0.,  0.,  0.,  0.]])

In [14]:
df_survival = df_sample_selected[["bcr_patient_barcode",  "PFI", "PFI.time"]]
df_survival.index = range(len(df_survival))

In [15]:
df_survival = df_survival.sort_values(by="PFI.time", ascending=False)
df_survival

    bcr_patient_barcode  PFI  PFI.time
268        TCGA-B6-A0RN    0    8008.0
263        TCGA-B6-A0RE    0    7777.0
274        TCGA-B6-A0RV    0    5156.0
279        TCGA-B6-A0WZ    1    5117.0
269        TCGA-B6-A0RO    0    4929.0
..                  ...  ...       ...
392        TCGA-C8-A1HJ    0       5.0
703        TCGA-PL-A8LX    0       5.0
404        TCGA-C8-A275    0       1.0
157        TCGA-AC-A7VC    0       1.0
702        TCGA-PL-A8LV    0       0.0

[726 rows x 3 columns]

In [16]:
np.savez_compressed("preprocessed/survival.npz", pfi=df_survival["PFI"], pfi_time=df_survival["PFI.time"])
np.savez_compressed("preprocessed/sort_order.npz", data=df_survival.index)

### merged_data 전처리

In [17]:
df_merged = pd.read_csv("final_data/merged_data.txt", sep="\t")
# for group
df_cnv = pd.read_csv("final_data/cnv_annotation.txt", sep="\t")
df_methyl = pd.read_csv("final_data/methyl_annotation.txt", sep="\t")
df_mrna = pd.read_csv("final_data/mrna_annotation.txt", sep="\t")
df_mutation = pd.read_csv("final_data/mutation_annotation.txt", sep="\t")

In [18]:
df_group = pd.concat((df_merged[["ID"]], df_merged[df_sample_selected["bcr_patient_barcode"]]), axis=1)
df_group

,ID,TCGA-3C-AAAU,TCGA-3C-AALI,TCGA-3C-AALJ,TCGA-3C-AALK,TCGA-4H-AAAK,TCGA-5L-AAT0,TCGA-5L-AAT1,TCGA-5T-A9QA,TCGA-A1-A0SB,...,TCGA-UL-AAZ6,TCGA-UU-A93S,TCGA-V7-A7HQ,TCGA-W8-A86G,TCGA-WT-AB41,TCGA-WT-AB44,TCGA-XX-A899,TCGA-XX-A89A,TCGA-Z7-A8R5,TCGA-Z7-A8R6
0,P53__TP53__P04637__95__289,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,1.000
1,Ras__KRAS__P01116__5__165,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
2,PI3Ka__PIK3CA__P42336__519__704,0.000,0.000,0.000,1.000,0.000,0.000,1.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,1.000,0.000,0.000
3,Pkinase_Tyr__BRAF__P15056__457__714,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
4,Iso_dh__IDH1__O75874__9__401,0.000,0.000,0.000,0.000,0.000,0.000,2.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354516,ZYX|7791_mrna,11.777,12.427,12.415,12.475,11.981,12.013,12.110,11.654,12.595,...,12.024,12.450,12.656,12.439,12.705,13.417,12.322,12.420,12.705,11.733
354517,ZZEF1|23140_mrna,10.889,10.366,9.882,9.611,9.702,9.850,10.464,10.124,10.916,...,10.280,9.075,9.548,9.923,9.128,9.647,10.918,10.490,9.561,9.143
354518,ZZZ3|26009_mrna,10.206,8.672,8.996,9.455,9.786,10.054,9.154,8.788,10.489,...,8.284,8.598,8.251,9.768,8.170,8.795,9.390,9.899,9.554,8.855
354519,psiTPTE22|387590_mrna,1.445,9.857,5.184,6.079,7.556,6.427,5.879,2.221,9.112,...,3.558,3.042,8.170,7.789,4.877,9.504,6.636,7.884,7.906,4.451
354520,tAKR|389932_mrna,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.960,0.000,0.000

In [19]:
df_group_cnv = pd.merge(df_group, df_cnv[["ID", "Gene"]], how="outer", on="ID")
df_group_cnv

,ID,TCGA-3C-AAAU,TCGA-3C-AALI,TCGA-3C-AALJ,TCGA-3C-AALK,TCGA-4H-AAAK,TCGA-5L-AAT0,TCGA-5L-AAT1,TCGA-5T-A9QA,TCGA-A1-A0SB,...,TCGA-UU-A93S,TCGA-V7-A7HQ,TCGA-W8-A86G,TCGA-WT-AB41,TCGA-WT-AB44,TCGA-XX-A899,TCGA-XX-A89A,TCGA-Z7-A8R5,TCGA-Z7-A8R6,Gene
0,P53__TP53__P04637__95__289,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,1.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,1.000,NaN
1,Ras__KRAS__P01116__5__165,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN
2,PI3Ka__PIK3CA__P42336__519__704,0.000,0.000,0.000,1.000,0.000,0.000,1.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,1.000,0.000,0.000,NaN
3,Pkinase_Tyr__BRAF__P15056__457__714,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN
4,Iso_dh__IDH1__O75874__9__401,0.000,0.000,0.000,0.000,0.000,0.000,2.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354516,ZYX|7791_mrna,11.777,12.427,12.415,12.475,11.981,12.013,12.110,11.654,12.595,...,12.450,12.656,12.439,12.705,13.417,12.322,12.420,12.705,11.733,NaN
354517,ZZEF1|23140_mrna,10.889,10.366,9.882,9.611,9.702,9.850,10.464,10.124,10.916,...,9.075,9.548,9.923,9.128,9.647,10.918,10.490,9.561,9.143,NaN
354518,ZZZ3|26009_mrna,10.206,8.672,8.996,9.455,9.786,10.054,9.154,8.788,10.489,...,8.598,8.251,9.768,8.170,8.795,9.390,9.899,9.554,8.855,NaN
354519,psiTPTE22|387590_mrna,1.445,9.857,5.184,6.079,7.556,6.427,5.879,2.221,9.112,...,3.042,8.170,7.789,4.877,9.504,6.636,7.884,7.906,4.451,NaN
354520,tAKR|389932_mrna,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.960,0.000,0.000,NaN

In [20]:
df_group_cnv_methly = pd.merge(df_group_cnv, df_methyl[["ID", "Gene_Symbol"]], how="outer", on="ID")
df_group_cnv_methly

,ID,TCGA-3C-AAAU,TCGA-3C-AALI,TCGA-3C-AALJ,TCGA-3C-AALK,TCGA-4H-AAAK,TCGA-5L-AAT0,TCGA-5L-AAT1,TCGA-5T-A9QA,TCGA-A1-A0SB,...,TCGA-V7-A7HQ,TCGA-W8-A86G,TCGA-WT-AB41,TCGA-WT-AB44,TCGA-XX-A899,TCGA-XX-A89A,TCGA-Z7-A8R5,TCGA-Z7-A8R6,Gene,Gene_Symbol
0,P53__TP53__P04637__95__289,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,1.000,NaN,NaN
1,Ras__KRAS__P01116__5__165,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN,NaN
2,PI3Ka__PIK3CA__P42336__519__704,0.000,0.000,0.000,1.000,0.000,0.000,1.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,1.000,0.000,0.000,NaN,NaN
3,Pkinase_Tyr__BRAF__P15056__457__714,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN,NaN
4,Iso_dh__IDH1__O75874__9__401,0.000,0.000,0.000,0.000,0.000,0.000,2.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354516,ZYX|7791_mrna,11.777,12.427,12.415,12.475,11.981,12.013,12.110,11.654,12.595,...,12.656,12.439,12.705,13.417,12.322,12.420,12.705,11.733,NaN,NaN
354517,ZZEF1|23140_mrna,10.889,10.366,9.882,9.611,9.702,9.850,10.464,10.124,10.916,...,9.548,9.923,9.128,9.647,10.918,10.490,9.561,9.143,NaN,NaN
354518,ZZZ3|26009_mrna,10.206,8.672,8.996,9.455,9.786,10.054,9.154,8.788,10.489,...,8.251,9.768,8.170,8.795,9.390,9.899,9.554,8.855,NaN,NaN
354519,psiTPTE22|387590_mrna,1.445,9.857,5.184,6.079,7.556,6.427,5.879,2.221,9.112,...,8.170,7.789,4.877,9.504,6.636,7.884,7.906,4.451,NaN,NaN
354520,tAKR|389932_mrna,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.960,0.000,0.000,NaN,NaN

In [21]:
df_group_cnv_methly_mutation = pd.merge(df_group_cnv_methly, df_mutation[["ID", "gene_name"]], how="outer", on="ID")
df_group_cnv_methly_mutation

,ID,TCGA-3C-AAAU,TCGA-3C-AALI,TCGA-3C-AALJ,TCGA-3C-AALK,TCGA-4H-AAAK,TCGA-5L-AAT0,TCGA-5L-AAT1,TCGA-5T-A9QA,TCGA-A1-A0SB,...,TCGA-W8-A86G,TCGA-WT-AB41,TCGA-WT-AB44,TCGA-XX-A899,TCGA-XX-A89A,TCGA-Z7-A8R5,TCGA-Z7-A8R6,Gene,Gene_Symbol,gene_name
0,P53__TP53__P04637__95__289,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,1.000,NaN,NaN,TP53
1,Ras__KRAS__P01116__5__165,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN,NaN,KRAS
2,PI3Ka__PIK3CA__P42336__519__704,0.000,0.000,0.000,1.000,0.000,0.000,1.000,0.000,0.000,...,0.000,0.000,0.000,0.000,1.000,0.000,0.000,NaN,NaN,PIK3CA
3,Pkinase_Tyr__BRAF__P15056__457__714,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN,NaN,BRAF
4,Iso_dh__IDH1__O75874__9__401,0.000,0.000,0.000,0.000,0.000,0.000,2.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN,NaN,IDH1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354516,ZYX|7791_mrna,11.777,12.427,12.415,12.475,11.981,12.013,12.110,11.654,12.595,...,12.439,12.705,13.417,12.322,12.420,12.705,11.733,NaN,NaN,NaN
354517,ZZEF1|23140_mrna,10.889,10.366,9.882,9.611,9.702,9.850,10.464,10.124,10.916,...,9.923,9.128,9.647,10.918,10.490,9.561,9.143,NaN,NaN,NaN
354518,ZZZ3|26009_mrna,10.206,8.672,8.996,9.455,9.786,10.054,9.154,8.788,10.489,...,9.768,8.170,8.795,9.390,9.899,9.554,8.855,NaN,NaN,NaN
354519,psiTPTE22|387590_mrna,1.445,9.857,5.184,6.079,7.556,6.427,5.879,2.221,9.112,...,7.789,4.877,9.504,6.636,7.884,7.906,4.451,NaN,NaN,NaN
354520,tAKR|389932_mrna,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.960,0.000,0.000,NaN,NaN,NaN

In [22]:
df_group_cnv_methly_mutation_mrna = pd.merge(df_group_cnv_methly_mutation, df_mrna, how="outer", left_on="ID", right_on="x")
df_group_cnv_methly_mutation_mrna

,ID,TCGA-3C-AAAU,TCGA-3C-AALI,TCGA-3C-AALJ,TCGA-3C-AALK,TCGA-4H-AAAK,TCGA-5L-AAT0,TCGA-5L-AAT1,TCGA-5T-A9QA,TCGA-A1-A0SB,...,TCGA-WT-AB41,TCGA-WT-AB44,TCGA-XX-A899,TCGA-XX-A89A,TCGA-Z7-A8R5,TCGA-Z7-A8R6,Gene,Gene_Symbol,gene_name,x
0,P53__TP53__P04637__95__289,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,1.000,NaN,NaN,TP53,NaN
1,Ras__KRAS__P01116__5__165,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,NaN,NaN,KRAS,NaN
2,PI3Ka__PIK3CA__P42336__519__704,0.000,0.000,0.000,1.000,0.000,0.000,1.000,0.000,0.000,...,0.000,0.000,0.000,1.000,0.000,0.000,NaN,NaN,PIK3CA,NaN
3,Pkinase_Tyr__BRAF__P15056__457__714,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,NaN,NaN,BRAF,NaN
4,Iso_dh__IDH1__O75874__9__401,0.000,0.000,0.000,0.000,0.000,0.000,2.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,NaN,NaN,IDH1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354516,ZYX|7791_mrna,11.777,12.427,12.415,12.475,11.981,12.013,12.110,11.654,12.595,...,12.705,13.417,12.322,12.420,12.705,11.733,NaN,NaN,NaN,ZYX|7791_mrna
354517,ZZEF1|23140_mrna,10.889,10.366,9.882,9.611,9.702,9.850,10.464,10.124,10.916,...,9.128,9.647,10.918,10.490,9.561,9.143,NaN,NaN,NaN,ZZEF1|23140_mrna
354518,ZZZ3|26009_mrna,10.206,8.672,8.996,9.455,9.786,10.054,9.154,8.788,10.489,...,8.170,8.795,9.390,9.899,9.554,8.855,NaN,NaN,NaN,ZZZ3|26009_mrna
354519,psiTPTE22|387590_mrna,1.445,9.857,5.184,6.079,7.556,6.427,5.879,2.221,9.112,...,4.877,9.504,6.636,7.884,7.906,4.451,NaN,NaN,NaN,psiTPTE22|387590_mrna
354520,tAKR|389932_mrna,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.960,0.000,0.000,NaN,NaN,NaN,tAKR|389932_mrna

In [23]:
df_group["group"] = df_group_cnv_methly_mutation_mrna["Gene"].fillna(df_group_cnv_methly_mutation_mrna["Gene_Symbol"]).fillna(df_group_cnv_methly_mutation_mrna["gene_name"]).fillna(df_group_cnv_methly_mutation_mrna["x"])
df_group = df_group.dropna(subset=["group", "ID"])
df_group.index = range(df_group.shape[0])
df_group

,ID,TCGA-3C-AAAU,TCGA-3C-AALI,TCGA-3C-AALJ,TCGA-3C-AALK,TCGA-4H-AAAK,TCGA-5L-AAT0,TCGA-5L-AAT1,TCGA-5T-A9QA,TCGA-A1-A0SB,...,TCGA-UU-A93S,TCGA-V7-A7HQ,TCGA-W8-A86G,TCGA-WT-AB41,TCGA-WT-AB44,TCGA-XX-A899,TCGA-XX-A89A,TCGA-Z7-A8R5,TCGA-Z7-A8R6,group
0,P53__TP53__P04637__95__289,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,1.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,1.000,TP53
1,Ras__KRAS__P01116__5__165,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,KRAS
2,PI3Ka__PIK3CA__P42336__519__704,0.000,0.000,0.000,1.000,0.000,0.000,1.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,1.000,0.000,0.000,PIK3CA
3,Pkinase_Tyr__BRAF__P15056__457__714,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,BRAF
4,Iso_dh__IDH1__O75874__9__401,0.000,0.000,0.000,0.000,0.000,0.000,2.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,IDH1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354496,ZYX|7791_mrna,11.777,12.427,12.415,12.475,11.981,12.013,12.110,11.654,12.595,...,12.450,12.656,12.439,12.705,13.417,12.322,12.420,12.705,11.733,ZYX|7791_mrna
354497,ZZEF1|23140_mrna,10.889,10.366,9.882,9.611,9.702,9.850,10.464,10.124,10.916,...,9.075,9.548,9.923,9.128,9.647,10.918,10.490,9.561,9.143,ZZEF1|23140_mrna
354498,ZZZ3|26009_mrna,10.206,8.672,8.996,9.455,9.786,10.054,9.154,8.788,10.489,...,8.598,8.251,9.768,8.170,8.795,9.390,9.899,9.554,8.855,ZZZ3|26009_mrna
354499,psiTPTE22|387590_mrna,1.445,9.857,5.184,6.079,7.556,6.427,5.879,2.221,9.112,...,3.042,8.170,7.789,4.877,9.504,6.636,7.884,7.906,4.451,psiTPTE22|387590_mrna
354500,tAKR|389932_mrna,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.960,0.000,0.000,tAKR|389932_mrna

In [36]:
# select only mrna
df_group = df_group_cnv_methly_mutation_mrna.dropna(subset=["x", "ID"])
df_group = df_group.drop(columns=["Gene", "Gene_Symbol", "gene_name"])
df_group = df_group.rename(columns={"x": "group"})
df_group.index = range(df_group.shape[0])
df_group

,ID,TCGA-3C-AAAU,TCGA-3C-AALI,TCGA-3C-AALJ,TCGA-3C-AALK,TCGA-4H-AAAK,TCGA-5L-AAT0,TCGA-5L-AAT1,TCGA-5T-A9QA,TCGA-A1-A0SB,...,TCGA-UU-A93S,TCGA-V7-A7HQ,TCGA-W8-A86G,TCGA-WT-AB41,TCGA-WT-AB44,TCGA-XX-A899,TCGA-XX-A89A,TCGA-Z7-A8R5,TCGA-Z7-A8R6,group
0,?|100130426_mrna,0.000,0.000,0.931,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,?|100130426_mrna
1,?|100133144_mrna,4.118,3.360,3.658,3.710,2.972,2.319,0.000,1.301,4.030,...,2.409,0.000,2.714,0.000,0.000,3.944,4.544,1.707,2.979,?|100133144_mrna
2,?|100134869_mrna,3.800,4.200,3.355,3.595,3.948,3.869,3.535,3.321,3.944,...,3.571,2.028,3.942,2.870,2.090,4.488,4.821,3.052,4.688,?|100134869_mrna
3,?|10357_mrna,5.732,6.145,7.279,7.179,6.413,6.849,6.870,6.762,6.875,...,7.099,4.954,7.015,5.772,5.435,7.117,6.026,6.427,7.397,?|10357_mrna
4,?|10431_mrna,8.676,9.142,10.411,9.759,9.584,9.660,10.116,10.473,9.363,...,11.496,10.751,9.448,10.283,10.875,9.353,9.499,10.156,9.972,?|10431_mrna
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20526,ZYX|7791_mrna,11.777,12.427,12.415,12.475,11.981,12.013,12.110,11.654,12.595,...,12.450,12.656,12.439,12.705,13.417,12.322,12.420,12.705,11.733,ZYX|7791_mrna
20527,ZZEF1|23140_mrna,10.889,10.366,9.882,9.611,9.702,9.850,10.464,10.124,10.916,...,9.075,9.548,9.923,9.128,9.647,10.918,10.490,9.561,9.143,ZZEF1|23140_mrna
20528,ZZZ3|26009_mrna,10.206,8.672,8.996,9.455,9.786,10.054,9.154,8.788,10.489,...,8.598,8.251,9.768,8.170,8.795,9.390,9.899,9.554,8.855,ZZZ3|26009_mrna
20529,psiTPTE22|387590_mrna,1.445,9.857,5.184,6.079,7.556,6.427,5.879,2.221,9.112,...,3.042,8.170,7.789,4.877,9.504,6.636,7.884,7.906,4.451,psiTPTE22|387590_mrna
20530,tAKR|389932_mrna,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.960,0.000,0.000,tAKR|389932_mrna

In [37]:
variable_to_index = dict()
group_to_index = dict()

k = 1
for i, row in df_group.iterrows():
    group = row["group"].split(";")
    for g in group:
        if g not in group_to_index.keys():
            group_to_index[g] = k
            k += 1

    variable = row["ID"]
    variable_to_index[variable] = i + 1

In [38]:
from collections import defaultdict

variable_to_groups = defaultdict(list)
group_to_variables = defaultdict(list)
for i, row in df_group.iterrows():
    # one variable multiple groups
    # if ";" in row["group"]:
    group = row["group"].split(";")
    variable = row["ID"]
    for g in group:
        variable_to_groups[variable].append(g)
        group_to_variables[g].append([variable])

In [39]:
import json

# root = "preprocessed"
root = "only_mrna"

with open(f"{root}/variable_to_index.json", "w") as json_file:
    json.dump(variable_to_index, json_file)

with open(f"{root}/index_to_variable.json", "w") as json_file:
    json.dump({value: key for key, value in variable_to_index.items()}, json_file)

with open(f"{root}/group_to_index.json", "w") as json_file:
    json.dump(group_to_index, json_file)

with open(f"{root}/index_to_group.json", "w") as json_file:
    json.dump({value: key for key, value in group_to_index.items()}, json_file)

with open(f"{root}/variable_to_groups.json", "w") as json_file:
    json.dump(variable_to_groups, json_file)

with open(f"{root}/group_to_variables.json", "w") as json_file:
    json.dump(group_to_variables, json_file)

In [40]:
len(group_to_variables.keys())

20531

In [41]:
list_group_to_variables = [[]] * (len(group_to_variables.keys()) + 1)
for group in group_to_variables.keys():
    group_index = group_to_index[group]
    list_group_to_variables[group_index] = []
    for value in group_to_variables[group]:
        list_group_to_variables[group_index].append(variable_to_index[value[0]])

In [42]:
import pickle

with open(f"{root}/group_to_variables_index.pkl", "wb") as f:
    pickle.dump(list_group_to_variables[1:], f)

In [43]:
array_group_clinical = np.concatenate((df_group.loc[:, df_group.columns[1:-1]].T.to_numpy(), df_clinical.to_numpy()), axis=1)
array_group_clinical.shape

(726, 20536)

In [44]:
array_predictor = (array_group_clinical - np.mean(array_group_clinical)) / np.std(array_group_clinical)

In [45]:
array_predictor[0]

array([-1.57921766, -0.56930162, -0.64728931, ..., -1.57921766,
       -1.57921766, -1.57921766])

In [46]:
array_predictor[df_survival.index.to_list()]

array([[-1.57921766, -1.12159179, -0.91264364, ..., -1.57921766,
        -1.57921766, -1.57921766],
       [-1.57921766, -0.98400974, -0.86997113, ..., -1.33397335,
        -1.57921766, -1.57921766],
       [-1.57921766, -0.73238908, -0.99847915, ..., -1.57921766,
        -1.57921766, -1.57921766],
       ...,
       [-1.57921766, -0.62472683, -0.78241892, ..., -1.57921766,
        -1.33397335, -1.57921766],
       [-1.57921766, -1.06910951, -0.48371136, ..., -1.57921766,
        -1.57921766, -1.57921766],
       [-1.44482378, -0.50087846, -0.32258585, ..., -1.33397335,
        -1.57921766, -1.57921766]])

In [47]:
np.savez_compressed(f"{root}/array_predictors.npz", data=array_predictor)